
---
apiVersion: v1
kind: Service
metadata:
  name: com-embedding-service
spec:
  selector:
    app.kubernetes.io/name: com-embedding
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-embedding
  labels:
    app: com-embedding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: com-embedding
  template:
    metadata:
      labels:
        app: com-embedding
    spec:
      containers:
      - name: com-embedding
        image: trieder83/com-embeddings:gpu-0.3
        env:
        - name: CHUNK_SIZE
          value: "50"
        - name: CHUNK_OVERLAP
          value: "5"
        command: ["flask", "--app embeddingsolr.py", "run", "--host 0.0.0.0", "--port 8888"]
        ports:
          - containerPort: 8888
        volumeMounts:
          - name: model
            mountPath: /data
      volumes:
        - name: model
          hostPath:
            path: /home/trieder/workspace/com-embeddings/data
